#if !canImport(ObjectiveC)
import XCTest

extension AvroDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvroDecoderTests = [
        ("testDecodeDouble", testDecodeDouble),
        ("testDecodeFloat", testDecodeFloat),
        ("testDecodeInt", testDecodeInt),
        ("testDecodeLong", testDecodeLong),
        ("testDecodeString", testDecodeString),
    ]
}

extension AvroFileContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvroFileContainerTests = [
        ("testFileContainer", testFileContainer),
    ]
}

extension AvroFileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvroFileTests = [
        ("testGPSDecode", testGPSDecode),
        ("testGPSEncode", testGPSEncode),
    ]
}

extension AvroSchemaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvroSchemaTests = [
        ("testArray", testArray),
        ("testArrayEquality", testArrayEquality),
        ("testArrayMap", testArrayMap),
        ("testEnum", testEnum),
        ("testEnumEquality", testEnumEquality),
        ("testFixed", testFixed),
        ("testFixedEquality", testFixedEquality),
        ("testMap", testMap),
        ("testMapEquality", testMapEquality),
        ("testPrimitive", testPrimitive),
        ("testRecord", testRecord),
        ("testRecordEquality", testRecordEquality),
        ("testUnion", testUnion),
        ("testUnionEquality", testUnionEquality),
        ("testUnionMap", testUnionMap),
    ]
}

extension AvroValueEncodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvroValueEncodingTests = [
        ("testEnumEncoding", testEnumEncoding),
    ]
}

extension AvroValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvroValueTests = [
        ("testArrayValue", testArrayValue),
        ("testBooleanValue", testBooleanValue),
        ("testByteValue", testByteValue),
        ("testDoubleValue", testDoubleValue),
        ("testEnumValue", testEnumValue),
        ("testFloatValue", testFloatValue),
        ("testIntValue", testIntValue),
        ("testLongValue", testLongValue),
        ("testMapValue", testMapValue),
        ("testStringValue", testStringValue),
        ("testUnionValue", testUnionValue),
    ]
}

extension VarintTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VarintTests = [
        ("testDecodeZigZag", testDecodeZigZag),
        ("testEncodeZigZag", testEncodeZigZag),
        ("testToInt", testToInt),
        ("testToUInt", testToUInt),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AvroDecoderTests.__allTests__AvroDecoderTests),
        testCase(AvroFileContainerTests.__allTests__AvroFileContainerTests),
        testCase(AvroFileTests.__allTests__AvroFileTests),
        testCase(AvroSchemaTests.__allTests__AvroSchemaTests),
        testCase(AvroValueEncodingTests.__allTests__AvroValueEncodingTests),
        testCase(AvroValueTests.__allTests__AvroValueTests),
        testCase(VarintTests.__allTests__VarintTests),
    ]
}
#endif
